apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
spec:
  selector:
    matchLabels:
      app: iris
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris
        image: store/intersystems/iris-community:2021.2.0.617.0 
        env:
        - name: ISC_DATA_DIRECTORY
          value: /storage/iris
        ports:
        - containerPort: 52773
          name: smp-http
        volumeMounts:
        - name: iris-sys-storage
          mountPath: /storage
      nodeSelector:
        worker: "yes"
      volumes:
      - name: iris-sys-storage
        persistentVolumeClaim:
          claimName: iris-pvc
